// 地图资源路径常量
export const MODEL_PATHS = {
  ROOM_LARGE: "/models/room-large.glb",
  ROOM_LARGE_VARIATION: "/models/room-large-variation.glb",
  ROOM_SMALL: "/models/room-small.glb",
  ROOM_SMALL_VARIATION: "/models/room-small-variation.glb",
  ROOM_WIDE: "/models/room-wide.glb",
  ROOM_WIDE_VARIATION: "/models/room-wide-variation.glb",
  ROOM_CORNER: "/models/room-corner.glb",
  CORRIDOR: "/models/corridor.glb",
  CORRIDOR_CORNER: "/models/corridor-corner.glb",
  CORRIDOR_WIDE: "/models/corridor-wide.glb",
  CORRIDOR_INTERSECTION: "/models/corridor-intersection.glb",
  CORRIDOR_JUNCTION: "/models/corridor-junction.glb",
  GATE_DOOR: "/models/gate-door.glb",
  STAIRS: "/models/stairs.glb",
  CHARACTER_A: "/models/character-a.glb",
  CHARACTER_B: "/models/character-b.glb",
  CHARACTER_C: "/models/character-c.glb",
  CHARACTER_D: "/models/character-d.glb",
  CHARACTER_E: "/models/character-e.glb",
  CHARACTER_F: "/models/character-f.glb",
  CHARACTER_G: "/models/character-g.glb",
  CHARACTER_H: "/models/character-h.glb",
} as const

export const MAP_PRELOAD_MODELS: string[] = [
  MODEL_PATHS.ROOM_LARGE,
  MODEL_PATHS.ROOM_LARGE_VARIATION,
  MODEL_PATHS.ROOM_SMALL,
  MODEL_PATHS.ROOM_SMALL_VARIATION,
  MODEL_PATHS.ROOM_WIDE,
  MODEL_PATHS.ROOM_WIDE_VARIATION,
  MODEL_PATHS.ROOM_CORNER,
  MODEL_PATHS.CORRIDOR,
  MODEL_PATHS.CORRIDOR_CORNER,
  MODEL_PATHS.CORRIDOR_WIDE,
  MODEL_PATHS.CORRIDOR_INTERSECTION,
  MODEL_PATHS.CORRIDOR_JUNCTION,
  MODEL_PATHS.GATE_DOOR,
  MODEL_PATHS.STAIRS,
]